/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.eria.application.main


import com.eria.http.HttpServer
import tornadofx.*


fun main(args: Array<String>) {
    when (checkInputRange(1..2, "Select use gui or cli", arrayOf("gui", "cli"))) {
        1 -> { //選擇Gui
            launch<GuiApp>(args)
            HttpServer.instance.stop()
        }
        2 -> { //選擇Cli
            openCli()
        }
    }
}


