/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.eria.application.main

import javafx.collections.FXCollections
import javafx.scene.control.TextField
import tornadofx.*

class MyApp: App(MyView::class)

fun main(args: Array<String>) {

    launch<MyApp>(args)
}

class MyView: View() {
    var portField: TextField by singleAssign()
    val texasCities = FXCollections.observableArrayList( "GET","POST")
    override val root = vbox {
        hbox {
            label("輸入port")
            portField = textfield()
        }
        combobox<String> {
            items = texasCities

        }
        button(" 開始"){
            action { }
        }

    }
}
